name: CI and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run VSCode Extension Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Run tests on Linux
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - name: Run tests on non-Linux
        run: npm test
        if: runner.os != 'Linux'

  release:
    name: Release
    runs-on: ubuntu-latest
    # Only run on push events to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # Optional: only run after tests have passed
    needs: test
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm clean-install

      - name: Verify dependency signatures
        run: npm audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx semantic-release
